# Generated by Django 5.0.1 on 2024-01-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_upcomingbill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='status',
            field=models.BooleanField(),
        ),
    ]
