# Generated by Django 5.0.1 on 2024-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_upcomingbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='status',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
