# Generated by Django 5.0.1 on 2024-01-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_upcomingbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
