# Generated by Django 5.0.1 on 2024-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_upcomingbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='due_date',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
