# Generated by Django 5.0.1 on 2024-01-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_upcomingbill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
