# Generated by Django 5.0.1 on 2024-01-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_upcomingbill_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingbill',
            options={'ordering': ['due_date']},
        ),
    ]
