# Generated by Django 5.0.1 on 2024-01-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one-time', 'One-time'), ('weekly', 'Weekly')], max_length=20),
        ),
    ]
