# Generated by Django 5.0.1 on 2024-01-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_of_category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
